// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsnuYpItgduk2vrlMtCQHCB6HNTeQ3Rp4',
    appId: '1:972977227359:web:5dec55a8d67bed5828bdea',
    messagingSenderId: '972977227359',
    projectId: 'arabicdictionary-69da8',
    authDomain: 'arabicdictionary-69da8.firebaseapp.com',
    storageBucket: 'arabicdictionary-69da8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1g5Ou_u9IporeeFH_x1F7K0VLaOsWru8',
    appId: '1:972977227359:android:f97491ca0bfcedf628bdea',
    messagingSenderId: '972977227359',
    projectId: 'arabicdictionary-69da8',
    storageBucket: 'arabicdictionary-69da8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9LZEv8xM3WU5VB5I1iFeHHAWGitiebYs',
    appId: '1:972977227359:ios:4984778a1b6df7ec28bdea',
    messagingSenderId: '972977227359',
    projectId: 'arabicdictionary-69da8',
    storageBucket: 'arabicdictionary-69da8.appspot.com',
    iosBundleId: 'com.arabicdictionaryforspeakersofotherlanguages.arabicdictionaryforspeakersofotherlanguages',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9LZEv8xM3WU5VB5I1iFeHHAWGitiebYs',
    appId: '1:972977227359:ios:55b79b5b2fadf7c728bdea',
    messagingSenderId: '972977227359',
    projectId: 'arabicdictionary-69da8',
    storageBucket: 'arabicdictionary-69da8.appspot.com',
    iosBundleId: 'com.arabicdictionaryforspeakersofotherlanguages.arabicdictionaryforspeakersofotherlanguages.RunnerTests',
  );
}
